#!/bin/sh

# You may find this shell script helpful.

java -server -mx1500m -cp classes \
  cs224n.assignments.MaximumEntropyClassifierTester \
  ../data/ner/genia >output.csv
./filter_errors.py <output.csv >filtered.csv
 ../bin/evalNER <output.csv
